name       : cereal
version    : 1.3.0
release    : 1
source     :
    - https://github.com/USCiLab/cereal/archive/v1.3.0.tar.gz : 329ea3e3130b026c03a4acc50e168e7daff4e6e661bc6a7dfec0d77b570851d5
license    : BSD-3-Clause
component  : programming.library
homepage   : http://uscilab.github.com/cereal
summary    : C++11 library for serialization
description: |
    cereal is a header-only C++11 serialization library. cereal takes arbitrary data types and reversibly turns them into different representations, such as compact binary encodings, XML, or JSON. cereal was designed to be fast, light-weight, and easy to extend - it has no external dependencies and can be easily bundled with other code or used standalone.
builddeps  :
    - doxygen
    - libboost-devel
patterns:
    - /*
setup      : |
    %cmake -DSKIP_PORTABILITY_TEST=ON
build      : |
    %make
install    : |
    %make_install
